openapi: 3.0.3
info:
  title: Products API
  description: Operating and get information of products
  version: v1
  contact:
    name: Hsieh-Te Hsieh
    url: https://github.com/arieshsieh0402
    email: hthsieh.law@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost/
security:
  - OAuth2:
    - full
paths:
  /auth/login:
    post:
      description: Login system
      summary: Login system
      tags:
        - login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  nullable: false
                  description: User's account
                  example: account
                password:
                  type: string
                  nullable: false
                  description: Password of user's account
                  example: password
      responses:
        '200':
          description: 登入成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  account:
                    type: string
                  name:
                    type: string
        '401':
          description: 帳號密碼錯誤
        '500':
          $ref: '#/components/responses/500'
  /goods/add:
    post:
      description: 新增商品
      summary: 新增商品
      tags:
        - goods
      operationId: postGood
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                goodsName:
                  type: string
                  nullable: false
                  description: Good's name
                  example: goods_name
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  goodsName:
                    type: string
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /goods:
    get:
      description: 取得所有商品
      summary: 取得所有商品
      tags:
        - goods
      operationId: getGoods
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GoodResource'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /goods/{id}:
    get:
      description: 取得指定商品
      summary: 取得指定商品
      tags:
        - goods
      operationId: getGoodById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodResource'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    put:
      description: 更新商品
      summary: 更新商品
      tags:
        - goods
      operationId: putGoodById
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                goodsName:
                  type: string
                  nullable: false
                  description: Good's name
                  example: goods_name
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoodResource'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    delete:
      description: 刪除商品
      summary: 刪除商品
      tags:
        - goods
      operationId: deleteGoodById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: 成功
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: 商品代號
      schema:
        type: string
  responses:
    '403':
      description: 權限不足
    '500':
      description: 系統錯誤
  schemas:
    GoodType:
      type: string
      enum: [goods]
    GoodResource:
      type: object
      properties:
        _id:
          type: string
        goodsName:
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://localhost/oauth/token'
          scopes:
            full: Full access to the API
